name: Deploy Flask App

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types: [completed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Flask App
        run: |
          export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
          export DOCKER_TAG=${{ github.event.workflow_run.head_sha }}

          docker compose down
          docker compose up -d --force-recreate --pull always
